plugins = []
headers = []
redirects = []

[functions]

  [functions."*"]

[build]
publish = "/Users/romanroth01/HD Projects/_A [HD]/Website-HyCoffee/dist"
publishOrigin = "ui"
commandOrigin = "ui"
command = "npm run build"

  [build.environment]

  [build.processing]

    [build.processing.css]

    [build.processing.html]

    [build.processing.images]

    [build.processing.js]

  [build.services]